# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24af2d059e284661676687c4107912ccc0e7702988b1b65c9af6764caaab402e4465aaed94f32e4d0e6ce9c3df9689dbbe35cd621da7650d46f85af052460550

test:
  secret_key_base: 7f053735dacc54b1d1c15e5be95c5e70239dac5142ed498d484f38702c147751315ddb0f30614cc10356268664e467544a8032a74c3bdb189297d3543d0256d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
